# Generated by Django 4.1 on 2022-09-18 00:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionarios', '0002_alter_funcionario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
